name: 'Build and Push Application'

on:
  push:
    branches: [main, develop]
    paths: ['app/**']
  pull_request:
    branches: [main]
    paths: ['app/**']
  workflow_dispatch:

env:
  REGISTRY: cst8918weatheracr.azurecr.io

jobs:
  build-and-push:
    name: 'Build and Push Docker Images'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use container driver so GHA cache works and make this builder the default
      - name: Set up Docker Buildx (docker-container)
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          use: true

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./app/backend
          file: ./app/backend/Dockerfile
          push: true
          # use comma-separated list to avoid YAML weirdness
          tags: ${{ env.REGISTRY }}/weather-backend:${{ github.sha }},${{ env.REGISTRY }}/weather-backend:${{ github.ref_name }},${{ env.REGISTRY }}/weather-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./app/frontend
          file: ./app/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/weather-frontend:${{ github.sha }},${{ env.REGISTRY }}/weather-frontend:${{ github.ref_name }},${{ env.REGISTRY }}/weather-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
