name: Static Analysis

on:
  push:
    branches: [main]
    paths:
      - '**/*.tf'
      - 'app/**'
      - '.github/workflows/static-analysis.yml'
  workflow_dispatch:

jobs:
  noop:
    name: No-op
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Static analysis not configured yet."
