name: 'Terraform Apply'

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-*.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options: [dev, test, prod]

env:
  # Auth for azurerm provider (taken from your AZURE_CREDENTIALS secret)
  ARM_CLIENT_ID:       ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
  ARM_CLIENT_SECRET:   ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
  ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
  ARM_TENANT_ID:       ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        environment: ${{ github.event_name == 'workflow_dispatch'
          && fromJSON(format('["{0}"]', github.event.inputs.environment))
          || fromJSON('["dev","test"]') }}
    environment: ${{ matrix.environment }}
    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/${{ matrix.environment }}
    # Make TF non-interactive and provide required variables
    env:
      TF_INPUT: "false"
      TF_VAR_openweather_api_key: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      # ---------- Idempotent imports so apply won't fail on existing resources ----------
      - name: Import Resource Group (idempotent)
        run: |
          terraform import azurerm_resource_group.main \
            "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/cst8918-final-project-group-5-${{ matrix.environment }}" || true

      - name: Import AKS (idempotent)
        run: |
          terraform import azurerm_kubernetes_cluster.dev \
            "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/cst8918-final-project-group-5-${{ matrix.environment }}/providers/Microsoft.ContainerService/managedClusters/${{ matrix.environment }}-weather-aks" || true

      - name: Import ACR (idempotent)
        run: |
          terraform import azurerm_container_registry.dev \
            "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/cst8918-final-project-group-5-${{ matrix.environment }}/providers/Microsoft.ContainerRegistry/registries/cst8918weatheracr${{ matrix.environment }}" || true

      # ---------- Plan first; only apply when there are changes ----------
      - name: Terraform Plan (detect changes)
        id: plan
        run: |
          set +e
          terraform plan -detailed-exitcode -no-color -out=tfplan
          CODE=$?
          echo "PLAN_EXIT=$CODE" >> $GITHUB_ENV
          # 0=no changes, 2=changes, 1=error (we'll handle below)
          exit 0

      - name: Terraform Apply (only if changes)
        if: env.PLAN_EXIT == '2'
        run: terraform apply -auto-approve tfplan

      - name: No changes to apply
        if: env.PLAN_EXIT == '0'
        run: echo "✅ No changes. Skipping terraform apply."

      - name: Fail on plan error
        if: env.PLAN_EXIT == '1'
        run: |
          echo "❌ terraform plan returned an error (exit code 1)."
          exit 1
